SELECT 
  t.PRODUCT_ID, 
  t.PRODUCT_NAME, 
  SUM(t.TOTAL_SALES) AS TOTAL_SALES
FROM (
  SELECT 
    fo.PRODUCT_ID, 
    fd.PRODUCT_NAME, 
    fo.AMOUNT * fd.PRICE AS TOTAL_SALES
  FROM FOOD_ORDER fo
  LEFT JOIN FOOD_PRODUCT fd
    ON fo.PRODUCT_ID = fd.PRODUCT_ID
  WHERE DATE_FORMAT(fo.PRODUCE_DATE, '%Y%m') = '202205'
) t
GROUP BY t.PRODUCT_ID, t.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC,fo.PRODUCT_ID asc;
