WITH TEMP AS (
  SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAX_SIZE
  FROM ECOLI_DATA 
  GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT 
  TEMP.YEAR AS YEAR,
  TEMP.MAX_SIZE - ECOLI_DATA.SIZE_OF_COLONY AS YEAR_DEV,
  ECOLI_DATA.ID
FROM ECOLI_DATA
JOIN TEMP
  ON YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = TEMP.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;