WITH TMP AS (
SELECT A.ID,B.FISH_NAME,A.LENGTH
FROM FISH_INFO A, FISH_NAME_INFO B
WHERE A.FISH_TYPE=B.FISH_TYPE)
SELECT ID,FISH_NAME,LENGTH FROM TMP
WHERE (FISH_NAME,LENGTH) IN (
SELECT FISH_NAME,MAX(LENGTH) FROM TMP
GROUP BY FISH_NAME)
ORDER BY ID ASC